[package]
name = "control2json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
control-file = { path = "../../lib/control-file/", version = "0.1.0" }
