[package]
name = "debnix"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Translate debian library names to their corresponding names in nixpkgs."

[workspace]
members = [
    ".",
    "lib/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
clap_complete = "3.2.4"
csv = "1.1.6"
debcontrol = "0.1.1"
log = "0.4"
pretty_env_logger = "0.3"
regex = "1.6.0"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = { version = "1.0.143", features = ["serde_derive"] }
serde_json = "1.0.83"
thiserror = "1.0.32"
control-file = { path = "./lib/control-file/", version = "0.1.0" }

